### ISSUE TITLE
Metric CSS is a pain point

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#100]
**What's the problem you want to solved?** I thought the metric-derived CSS variables were cute and fun, but I tried to edit the CSS today and I couldn't remember whether to use `--micro` or `--milli` for half-size. Boo.

**Is there a solution you'd like to recommend?** Maybe we should just do:

```css
:root {
  --three: calc(var(--one) * 3);
  --two: calc(var(--one) * 2);
  --one: 1rem;
  --half: calc(var(--base) / 2);
  --third: calc(var(--base) / 3);
  --quarter: calc(var(--base) / 4);
}
```

This has the nice side-effect of being able to easily change the base, so we could use 1.5rem or the golden ratio or whatever we want in the future without having to memorize quirky variables names. Simplicity!!!!!
