### ISSUE TITLE
Imitate Mastodon UX for expanding posts with content warnings

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#85]
Perhaps we should copy the UX from Mastodon for expanding posts with content warnings. The arrow icon is quite ambiguous. 

### Show more
![Screenshot from 2020-01-26 22-05-43](https://user-images.githubusercontent.com/18296993/73142571-3361d180-4088-11ea-9865-38e0163c7b40.png)

### Show Less
![Screenshot from 2020-01-26 22-08-54](https://user-images.githubusercontent.com/18296993/73142600-8c316a00-4088-11ea-85af-2e96ef1f9b23.png)

## With Arrow
![oasis_content_warning_mockup](https://user-images.githubusercontent.com/18296993/73142657-2e515200-4089-11ea-9d9f-08d15567e2b2.png)
Not sure if the arrow is still necessary at that point but I kind of like it.

## Without Arrow
![oasis_content_warning_mockup_noarrow](https://user-images.githubusercontent.com/18296993/73142703-d535ee00-4089-11ea-9f2f-7d2a2840dc8f.png)

**Comment by georgeowell** [comment]
## Without Arrow and Box
![oasis_content_warning_mockup_noarrow_nobox](https://user-images.githubusercontent.com/18296993/73142874-796c6480-408b-11ea-9cc9-eae4fb5ee6fe.png)
Perhaps even no box either. This looks very clean IMO.

**Comment by jedahan** [comment]
I wonder if it would look well as one big button

> Show "Tech, XMPP, OMEMO, Rant"

**Comment by christianbundy** [comment]
btw here's a quick CSS sketch to get a simple 'show more' / 'show less' button

```css
summary {
  border: none;
  list-style: none;
}

summary::after {
    content: "show more";
    background: var(--fg-status);
    margin-left: var(--milli);
    border-radius: var(--common-radius);
    white-space: nowrap;
    padding: var(--nano) var(--micro);
    font-size: 85%;
    color: var(--bg);
}

details[open] > summary::after {
  content: "show less";
}
```

![Screenshot from 2020-01-26 21-33-57](https://user-images.githubusercontent.com/537700/73152162-969d3500-4083-11ea-9b68-fd5778746364.png)
